# Generated by Django 6.0.6 on 2026-07-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_title', models.CharField(max_length=255)),
                ('site_description', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='marketing/logo/')),
                ('favicon', models.ImageField(upload_to='marketing/favicon/')),
                ('copyright_text', models.CharField(max_length=255)),
                ('primary_color', models.CharField(default='#0f4c81', max_length=20)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Setting',
            },
        ),
    ]
