# Generated by Django 6.0.6 on 2026-07-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtm_id', models.CharField(blank=True, max_length=50, verbose_name='Google Tag Manager ID')),
                ('ga4_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics GA4 ID')),
                ('meta_pixel_id', models.CharField(blank=True, max_length=100, verbose_name='Meta/Facebook Pixel ID')),
                ('tiktok_pixel_id', models.CharField(blank=True, max_length=100, verbose_name='TikTok Pixel ID')),
                ('google_ads_id', models.CharField(blank=True, max_length=100, verbose_name='Google Ads ID')),
                ('hotjar_id', models.CharField(blank=True, max_length=100, verbose_name='Hotjar ID')),
                ('clarity_id', models.CharField(blank=True, max_length=100, verbose_name='Microsoft Clarity ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking Setting',
                'verbose_name_plural': 'Tracking Setting',
            },
        ),
    ]
