# Generated by Django 6.0.6 on 2026-07-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_trackingsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Setting',
            },
        ),
    ]
