# Generated by Django 6.0.6 on 2026-07-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_seosetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraphSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_title', models.CharField(max_length=255)),
                ('og_description', models.TextField()),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='marketing/opengraph/')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=100)),
                ('facebook_app_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Open Graph Setting',
                'verbose_name_plural': 'Open Graph Setting',
            },
        ),
    ]
