# Generated by Django 6.0.6 on 2026-07-07 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_opengraphsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adsense_publisher_id', models.CharField(blank=True, max_length=100)),
                ('enable_ads', models.BooleanField(default=False)),
                ('header_ad_enabled', models.BooleanField(default=False)),
                ('sidebar_ad_enabled', models.BooleanField(default=False)),
                ('footer_ad_enabled', models.BooleanField(default=False)),
                ('article_ad_enabled', models.BooleanField(default=False)),
                ('sticky_ad_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Advertisement Setting',
                'verbose_name_plural': 'Advertisement Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_primary', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_support', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('google_map_url', models.URLField(blank=True)),
                ('office_hours', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Setting',
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='GeoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('default_locale', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Geo Setting',
                'verbose_name_plural': 'Geo Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('messenger', models.URLField(blank=True)),
                ('threads', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='VerificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_search_console', models.CharField(blank=True, max_length=255)),
                ('bing_webmaster', models.CharField(blank=True, max_length=255)),
                ('facebook_domain_verification', models.CharField(blank=True, max_length=255)),
                ('pinterest_verification', models.CharField(blank=True, max_length=255)),
                ('yandex_verification', models.CharField(blank=True, max_length=255)),
                ('apple_verification', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Verification Setting',
                'verbose_name_plural': 'Verification Settings',
            },
        ),
        migrations.AddField(
            model_name='opengraphsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seosetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackingsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
