# Generated by Django 6.0.2 on 2026-06-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspagebackend', '0002_homepageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_images/', verbose_name='ছবি')),
                ('position', models.CharField(choices=[('left', 'বাম'), ('center', 'মাঝখান'), ('right', 'ডান'), ('full', 'পূর্ণ প্রস্থ')], default='left', max_length=10, verbose_name='অবস্থান')),
                ('col_span', models.CharField(choices=[('1', '১ কলাম'), ('2', '২ কলাম'), ('3', '৩ কলাম'), ('4', '৪ কলাম'), ('6', '৬ কলাম (পূর্ণ)')], default='3', max_length=2, verbose_name='কলাম সাইজ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newspagebackend.page', verbose_name='পাতা')),
            ],
            options={
                'verbose_name': 'পাতার ছবি',
                'verbose_name_plural': 'পাতার ছবিসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='HomePageImage',
        ),
    ]
