# Generated by Django 6.0.2 on 2026-06-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspagebackend', '0003_pageimage_delete_homepageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/', verbose_name='ছবি')),
                ('position', models.CharField(choices=[('left', 'বাম'), ('center', 'মাঝখান'), ('right', 'ডান')], default='center', max_length=10, verbose_name='অবস্থান')),
                ('size', models.CharField(choices=[('small', 'ছোট'), ('medium', 'মাঝারি'), ('large', 'বড়'), ('full', 'পূর্ণ')], default='medium', max_length=10, verbose_name='সাইজ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'হোম পেজ ছবি',
                'verbose_name_plural': 'হোম পেজ ছবিসমূহ',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='PageImage',
        ),
    ]
