# Generated by Django 6.0.2 on 2026-06-27 07:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspagebackend', '0004_homepageimage_delete_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='কন্টেন্ট (CKEditor)'),
        ),
    ]
