# Generated by Django 6.0.2 on 2026-07-05 10:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspagebackend', '0005_homepageimage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageimage',
            options={'ordering': ['order'], 'verbose_name': 'Center Content', 'verbose_name_plural': 'Center Content'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='title',
            field=models.CharField(default='Home Page', max_length=100, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content (CKEditor)'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('full', 'Full')], default='medium', max_length=10, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Page Name'),
        ),
    ]
